#!/bin/bash

# Set environment
module purge
module load NEMO/prg-env

export OMP_NUM_THREADS=1

# Compile tools
while read -r LINE; do
  CFG=${LINE%% *}
  ./makenemo -m Anemone-ifort-xios3 -j 32 -r "$CFG" || exit
done <cfgs/work_cfgs.txt
