#!/bin/bash

# Set environment
module load PrgEnv-cray/8.4.0
module load cce/16.0.1
module load cray-hdf5-parallel/1.12.2.7
module load cray-netcdf-hdf5parallel/4.9.0.7

module list
export OMP_NUM_THREADS=1

# Compile tools
while read -r LINE; do
  CFG=${LINE%% *}
  ./makenemo -m X86_ARCHER2-Cray-xios3 -j 16 -r "$CFG" || exit
done <cfgs/work_cfgs.txt
