#!/bin/bash

# Set environment
module purge
module load NEMO/prg-env

export OMP_NUM_THREADS=1

# Compile tools
for TOOL in DOMAINcfg REBUILD_NEMO WEIGHTS; do
    ./maketools -m Anemone-ifort -j 32 -n $TOOL || exit
done
