#!/bin/bash

# Set environment
module purge
module load lmod
module load slurm/21.08.5
module load NEMO/prg-env

export OMP_NUM_THREADS=1

# Compile tools
while read -r LINE; do
  CFG=${LINE%% *}
  ./makenemo -m Anemone-ifort -j 16 -r "$CFG" || exit
done <cfgs/work_cfgs.txt
