#!/bin/bash

# Set environment
module load cray-mpich/8.1.23
module load cray-hdf5-parallel/1.12.2.1
module load cray-netcdf-hdf5parallel/4.9.0.1

module list
export OMP_NUM_THREADS=1

# Compile tools
for TOOL in DOMAINcfg REBUILD_NEMO WEIGHTS; do
    ./maketools -m X86_ARCHER2-Cray-xios3 -j 16 -n $TOOL || exit
done
