#!/bin/bash

# Set environment
module swap PrgEnv-cray/8.0.0 PrgEnv-gnu/8.1.0
module swap craype-network-ofi craype-network-ucx
module swap cray-mpich cray-mpich-ucx
module load cray-hdf5-parallel/1.12.0.7
module load cray-netcdf-hdf5parallel/4.7.4.7
module load libfabric
module list
export OMP_NUM_THREADS=1

# Compile tools
while read -r LINE; do
  CFG=${LINE%% *}
  ./makenemo -m X86_ARCHER2-Gnu_4.2 -j 16 -r "$CFG" || exit
done <cfgs/work_cfgs.txt
