#!/bin/bash

WD=$PWD

SYSTEM=Archer2

BRANCH=4.2.0
#COMMIT=

NEMODIR=${WD}/nemo
STOP=0

# Handle arguments
usage() { echo "Usage: $0 [-b branch] [-c commit] [-d directory] [-s system] [-x stop_after_download]" 1>&2; exit 1; }
while getopts ":b:c:d:s:x" o; do
    case "${o}" in
        b)
            BRANCH=${OPTARG}
            ;;
        c)
            COMMIT=${OPTARG}
            ;;
        d)
            NEMODIR=$(realpath "${OPTARG}")
            ;;
        s)
            SYSTEM=${OPTARG}
            ;;
        x)
            STOP=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Check system is supported and ensure 'correct' case of $SYSTEM
if [[ "$SYSTEM" =~ ^([aA][nN][eE][mM][oO][nN][eE])$ ]]; then
      SYSTEM=Anemone
    elif [[ "$SYSTEM" =~ ^([aA][rR][cC][hH][eE][rR][2])$ ]]; then
      SYSTEM=Archer2
    else
      echo "System not recognised. Options are: Anemone, Archer2"
    exit
fi


# Download NEMO
echo "Downloading NEMO"

# Checkout the NEMO code from the SVN Paris repository
#svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/r4.0/r$NEMO_VER --depth empty ${NEMODIR}
#svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/r4.0/r$NEMO_VER/src --depth infinity ${NEMODIR}/src
#svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/r4.0/r$NEMO_VER/cfgs/SHARED nemo/cfgs/SHARED
#svn export http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/r4.0/r$NEMO_VER/cfgs/ref_cfgs.txt nemo/cfgs/ref_cfgs.txt

# Checking out from NEMO GitLab
git clone https://forge.nemo-ocean.eu/nemo/nemo.git -b "$BRANCH" "$NEMODIR" || exit
if [ -n "${COMMIT}" ]; then
    cd "$NEMODIR" || exit
    git reset --hard "$COMMIT" || exit
    cd "$WD" || exit
fi

if [[ "$STOP" == 1 ]]; then
    exit
fi

# Add commas to namelists
#echo "Adding commas to namelists"
#for BOOL in true false TRUE FALSE; do
#    find "$NEMODIR"/. -type f \( -name "*namelist*_ref" -o -name "*namelist*_cfg" \) -exec perl -pi -e "s/.$BOOL.(?!\s*,)/.$BOOL.,/g" {} +
#done

###########################################
# SYSTEM
###########################################
# System specific options
echo "Setting up configuration and scripts for ${SYSTEM}"

echo $PWD

ln -sfT compile_nemo_${SYSTEM} scripts/compile_nemo
ln -sfT compile_tools_${SYSTEM} scripts/compile_tools
ln -sfT mkslurm_NPD_${SYSTEM} scripts/python/mkslurm_NPD

ln -sfT INPUT_${SYSTEM} data/INPUT


# Copy
echo "Copying customized files into ${NEMODIR}"
cp -r "${WD}"/{arch,cfgs,data,ext,scripts,tools} "$NEMODIR"/. || exit


###########################################
# TOOLS
###########################################
# Compile tools
echo "Compiling tools"
cd "$NEMODIR"/tools || exit
../scripts/compile_tools || exit

## Submit DOMAINcfg
#echo "Submitting scripts to create domain files"
#for DIR in "${WD}"/tools/DOMAINcfg/*/; do
#    DIR=$(basename "$DIR")
#    echo "$DIR"
#    cd "$NEMODIR"/tools/DOMAINcfg/"$DIR"/ || exit
#    if [ "$DIR" == "eORCA12_GSRIDGE36Z-GIBSTRA36Z" ] ; then
#        DOMAIN_JOBID=$(sbatch --parsable build_domains.slurm) || exit
#    else
#        sbatch build_domains.slurm || exit
#    fi
#done
#
## Submit WEIGHTS
#echo "Submitting scripts to create weights"
#for DIR in "${WD}"/tools/WEIGHTS/*/; do
#    DIR=$(basename "$DIR")
#    echo "$DIR"
#    cd "$NEMODIR"/tools/WEIGHTS/"$DIR"/ || exit
#    sbatch --dependency=afterok:"$DOMAIN_JOBID" build_weights.slurm || exit
#done

###########################################
# CONFIGURATIONS
###########################################

# Add and compile cfgs
echo "Compiling NEMO"
cd "$NEMODIR" || exit
./scripts/compile_nemo || exit

# Bye-Bye
squeue -u "$USER"
cd "$WD" || exit
